### PR TITLE
feat: job_service now works with uid's. This makes jobs deletable

### LINKED ISSUE #1313: Rework JobAPI to handle delete (probably means uuid for jobs)

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- JobService now works with UID for started jobs
- Enable delete button on "AnalysisJobTable"

## Why is this pull request needed?
- Should be possible to delete jobs

## Issues related to this change
closes #1313

### CODE REVIEW

**Review by KristianKjerstad — COMMENTED** [review]
I am not sure if delete jobs will work 100%, since the referenceTarget attribute for a Job does not seem to be updated when deleting jobs.

I think there is a bug if the user:
1) creates a new job
2) delete some other job
3) start the newly created job

The bug will probably appear if user deletes something while a job is running, but before the result is uploaded.

**Review by netr0m — CHANGES_REQUESTED** [review]
Looks good, but what Kristian mentions should be checked

**Review by eoaksnes — APPROVED** [review]
Look good, but same comment as Morten, ref Kristian

**Comment by KristianKjerstad** [comment]
when testing, I could not fetch logs for a job. looks like jobUID in JobControl.tsx is undefined, whcich causes the useEffect to stop on the line "if (!jobUID) return"

maybe the jobUID comonent state is not initialized correctly?

**Pull request merged**
